#!/usr/bin/env python

import os
import sys

from AutoItLibrary import AutoItLibrary

class AutoItLibrary(AutoItLibrary):
    """Example library to be used with Robot Framework's remote server.

    This documentation is visible in docs generated by _libdoc.py_
    starting from Robot Framework 2.6.2.
    """
    def __init__(self):
        AutoItLibrary.__init__(self, "E:\KeywordAutomation\TestLib","60",True)

if __name__ == '__main__':
    from robotremoteserver import RobotRemoteServer
    RobotRemoteServer(AutoItLibrary(), *sys.argv[1:])
