language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
# command to run tests
install:
  - pip install -U pip setuptools
  - pip install -U -r test_require.txt
script:
  - python setup.py test
